#Networks
networks:
  # frontend:
  #   driver: bridge
  # Todos os serviços devem usar a rede BACKEND para interagirem entre si e com o BROKER
  backend:
    driver: bridge
  auth_db:
    driver: bridge
  cliente_db:
    driver: bridge
  gerente_db:
    driver: bridge
  conta_db:
    driver: bridge


#Volumes para persistencia do banco de dados
volumes:
  mongodb_server_data:
  cliente_pg_data:
  gerente_pg_data:
  conta_comm_pg_data:
  conta_query_pg_data:
  broker_data:


#Containers 
services:
  #Angular Frontend
  #! Não rolou, muito demorado pra subir e executar
  # bantads_frontend:
  #   container_name: bantads_frontend
  #   build:
  #     context: ./../frontend/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./../frontend/:/app:rw
  #   ports:
  #     - 4200:4200
  #     - 49153:49153
  #   networks:
  #     - frontend
  #   depends_on:
  #     - api_gateway

  #Broker RabbitMQ para SAGA Orquestrada
  bantads-broker:
    container_name: bantads-broker
    image: rabbitmq:3.10-management
    restart: on-failure
    volumes:
      - broker_data:/data
    ports:
      - 5672:5672 
      - 15672:15672
      - 15692:15692
    networks:
      - backend

  #Orquestrador SAGA
  bantads-saga:
    container_name: bantads-saga
    build:
      context: ./../bantads-saga
      dockerfile: Dockerfile
    ports:
      - 5004:8080
    environment:
      RABBITMQ_HOST: bantads-broker
    restart: on-failure
    depends_on:
      - bantads-broker
    networks:
      - backend

  # API Gateway
  api-gateway:
    # image: bantads-api-gateway
    container_name: bantads-api-gateway
    build:
      context: ./../api-gateway/
      dockerfile: APIGateway.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./../api-gateway/:/usr/src/app
    networks:
      - backend
    depends_on:
      - bantads-saga
      # - frontend

  # MongoDB AUTH Database
  bantads-authdb:
    container_name: bantads-authdb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: bantads
    volumes:
      - mongodb_server_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - auth_db

  #Authentication Service
  auth-ws:
    container_name: bantads-auth-ws
    build:
      context: ./../auth-ws
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    environment:
      MONGO_HOST: bantads-authdb
      RABBITMQ_HOST: bantads-broker
    restart: on-failure
    depends_on:
      - bantads-authdb
      - bantads-saga
      - bantads-broker
    networks:
      - auth_db
      - backend

  #Cliente DB
  cliente-db:
    container_name: bantads-cliente-db
    build:
      context: .
      dockerfile: ./Postgresql.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: pt_BR.UTF-8
    ports:
      - 5432:5432
    volumes:
      - cliente_pg_data:/var/lib/postgresql/data
    networks:
      - cliente_db

  #Cliente Service
  cliente-ws:
    container_name: bantads-cliente-ws
    build:
      context: ./../cliente-ws
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: cliente-db
      DATABASE_PORT: 5432
      RABBITMQ_HOST: bantads-broker
    restart: on-failure
    ports:
      - 5001:8080
    depends_on:
      - cliente-db
      - bantads-saga
    networks:
      - backend
      - cliente_db

  #Gerente DB
  gerente-db:
    container_name: bantads-gerente-db
    build:
      context: .
      dockerfile: ./Postgresql.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: pt_BR.UTF-8
    ports:
      - 5433:5432
    volumes:
      - gerente_pg_data:/var/lib/postgresql/data
    networks:
      - gerente_db

  #Cliente Service
  gerente-ws:
    container_name: bantads-gerente-ws
    build:
      context: ./../gerente-ws
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: gerente-db
      DATABASE_PORT: 5432
      RABBITMQ_HOST: bantads-broker
    restart: on-failure
    ports:
      - 5002:8080
    depends_on:
      - gerente-db
      - bantads-saga
    networks:
      - backend
      - gerente_db

  #Conta DB - COMMAND
  conta-command-db:
    container_name: bantads-conta-command-db
    build:
      context: .
      dockerfile: ./Postgresql.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: pt_BR.UTF-8
    ports:
      - 5434:5432
    volumes:
      - conta_comm_pg_data:/var/lib/postgresql/data
    networks:
      - conta_db

  #Conta DB - QUERY
  conta-query-db:
    container_name: bantads-conta-query-db
    build:
      context: .
      dockerfile: ./Postgresql.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: pt_BR.UTF-8
    ports:
      - 5435:5432
    volumes:
      - conta_query_pg_data:/var/lib/postgresql/data
    networks:
      - conta_db

  #Conta Service
  conta-ws:
    container_name: bantads-conta-ws
    build:
      context: ./../conta-ws
      dockerfile: Dockerfile
    environment:
      DB_COMMAND_HOST: conta-command-db
      DB_COMMAND_PORT: 5432
      DB_QUERY_HOST: conta-query-db
      DB_QUERY_PORT: 5432
      RABBITMQ_HOST: bantads-broker
    restart: on-failure
    ports:
      - 5003:8080
    depends_on:
      - conta-command-db
      - conta-query-db
      - bantads-saga
    networks:
      - backend
      - conta_db

  

